### ISSUE TITLE
Algorithm Discrepancies

### ISSUE THREAD

**Issue by blakeBam** [vc1492a/PyNomaly#20] opened 2018-11-15 22:42 UTC
Recently I've had to do outlier analysis for work and came across your package which neatly implements LoOP. When I was reading through the source code, I noticed two spots where the calculations don't seem to line up with what was described in the [paper](http://www.dbs.ifi.lmu.de/Publikationen/Papers/LoOP1649.pdf). There may be good reasons why it differs from the original algorithm (or I'm misreading it entirely).

1. When calculating the PLOF for an object O, the expected value used in this package is the expected value of every pdist value, where the paper says to just use the expected value for the pdist of objects that are in O's neighborhood

2. In the calculation of the nPLOF, first _prob_local_outlier_factors_ev calculates the expected value for PLOF squared just fine, but followed up after in _norm_prob_outlier_factor the value is again squared and sqaure rooted. The paper just specifies a square root and not another square.

I was just wondering if there was a reason for the deviation from the paper in these regards.
Thanks!

**Comment by vc1492a** [comment] 2018-11-16 02:45
@blakeBam Thanks for opening this issue and making the discrepancies apparent. The differences in implementation stem from the original problem in which the code behind PyNomaly was originally applied - these differences in implementation were not intended to be published in the broader PyNomaly release. I recently received an email from [aadharna](https://github.com/aadharna) indicating the same and we had some discussion around this topic, so this issue should be explored further.  

I'll endeavor to explore and address the issue soon - since you may have already identified the root causes though, I'd also gladly welcome a pull request if you'd like to go ahead and make the changes. The `multiple_gaussian_2d.py` file can be used to generate a plot similar to that in the original paper and used for comparison.

**Comment by blakeBam** [comment] 2018-11-16 15:55
@vc1492a I'll get to work on that. One issue I can see with relations to my problem, is how to handle the case where the points in a neighborhood of a point are the point itself. This would make the expected value 0 and the PLOF value infinite as well as the nPLOF value infinite. Do you know of a way to properly handle this situation?

**Comment by aadharna** [comment] 2018-11-16 18:08
@blakeBam 

Regarding 1): that's the error that @vc1492a  and I have talked about! Unfortunately grad school has been keeping me too busy to work on the problem, but I was planning on taking some time around christmas to dive in. It'll be interesting to see if what we individually come up with matches. 

Regarding 2): I actually hadn't noticed that!

**Comment by vc1492a** [comment] 2018-11-19 01:13
@blakeBam Thanks for your pull request - checked out your changes and they look great. I have merged [PR #21](https://github.com/vc1492a/PyNomaly/pull/21) with the `dev` branch, and an in the process of updating the automated tests and the stream approach. Once that's complete, I'll commit the changes and close this issue. Thanks!

**Comment by vc1492a** [comment] 2018-11-22 13:09
@blakeBam @aadharna Thank you both for making this issue apparent and for suggesting changes to the source code. I've updated the library to use the changes and committed the changes to git and PyPi as version 0.2.5. @blakeBam, I hope you find this library useful for your work! Thanks again.

**Closed by vc1492a** 2018-11-22 13:09 UTC
Labels: bug
